# Use the appropriate JDK version
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /notification_service

# Copy the JAR file to the working directory
COPY target/notification_service-0.0.1-SNAPSHOT.jar notification_service.jar

# Expose the port the service listens on
EXPOSE 8082

# Set the entry point to run the service
ENTRYPOINT ["java", "-jar", "notification_service.jar"]
