# Use Maven image to build the application
FROM maven:3.9.5-eclipse-temurin-21-alpine AS build

# Set the working directory inside the container
WORKDIR /api_gateway

#Copy only the necessary files for dependency resolution
COPY pom.xml ./
COPY src ./src

# Run Maven to clean, install dependencies, and build the application while skipping tests
RUN mvn clean install -DskipTests && mvn package -DskipTests

# Use a smaller JDK image to run the application
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /api_gateway

# Copy the JAR file from the build stage
COPY --from=build /api_gateway/target/api_gateway-0.0.1-SNAPSHOT.jar api_gateway.jar

# Expose the port the service listens on
EXPOSE 8000

# Set the entry point to run the service
ENTRYPOINT ["java", "-jar", "api_gateway.jar"]