eureka:
    instance:
        hostname: user-service
    client:
        serviceUrl:
            defaultZone: http://discovery-server:8761/eureka/

server:
    port: 8083

spring:
    application:
        name: user-service
    config:
        import: optional:configserver:http://config-server:8888
    datasource:
        url: jdbc:mysql://mysql:3306/whispers_of_zephyr_users
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 5
            minimum-idle: 2
            idle-timeout: 10000
            max-lifetime: 30000
            initialization-fail-timeout: -1
    jpa:
        hibernate:
            ddl-auto: update
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect

    rabbitmq:
        host: rabbitmq
        port: 5672
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}
    security:
        user:
            name: admin
            password: admin
