eureka:
    instance:
        hostname: discovery-server
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
    port: 8761

spring:
    application:
        name: discovery-server
    config:
        import: optional:configserver:http://config_server:8888
