# Use Maven image to build the application
FROM maven:3.9.5-eclipse-temurin-21-alpine AS build

# Set the working directory inside the container
WORKDIR /discovery_server

# Copy only the necessary files for dependency resolution
COPY pom.xml ./
COPY src ./src

# Run Maven to clean, install dependencies, and build the application while skipping tests
RUN mvn clean install -DskipTests && mvn package -DskipTests

# Use a smaller JDK image to run the application
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /discovery_server

# Copy the JAR file from the build stage
COPY --from=build /discovery_server/target/discovery_server-0.0.1-SNAPSHOT.jar discovery_server.jar

# Expose the port the service listens on
EXPOSE 8761

# Set the entry point to run the service
ENTRYPOINT ["java", "-jar", "discovery_server.jar"]
