# Use the appropriate JDK version
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /blog_service

# Copy the JAR file to the working directory
COPY target/blog_service-0.0.1-SNAPSHOT.jar blog_service.jar

# Expose the port the service listens on
EXPOSE 8080

# Set the entry point to run the service
ENTRYPOINT ["java", "-jar", "blog_service.jar"]
