# Use Maven image to build the application
FROM maven:3.9.5-eclipse-temurin-21-alpine AS build

# Set the working directory inside the container
WORKDIR /blog_service

# Copy only the necessary files for dependency resolution
COPY pom.xml ./
COPY src ./src

# Run Maven to build the application and skip tests
RUN mvn clean package -DskipTests

# Use a smaller JDK image to run the application
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /blog_service

# Copy the JAR file from the build stage
COPY --from=build /blog_service/target/blog_service-0.0.1-SNAPSHOT.jar blog_service.jar

# Expose the port the service listens on
EXPOSE 8080

# Set the entry point to run the service
ENTRYPOINT ["java", "-jar", "blog_service.jar"]
