eureka:
    instance:
        hostname: blog-service
    client:
        serviceUrl:
            defaultZone: http://discovery-server:8761/eureka/

server:
    port: 8080

spring:
    application:
        name: blog-service
    config:
        import: optional:configserver:http://config-server:8888
    datasource:
        url: jdbc:mysql://mysql:3306/whispers_of_zephyr_blogs
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
            enabled: true

    rabbitmq:
        host: rabbitmq
        port: 5672
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}

custom:
    image:
        path: "/utils/default blog image.jpeg"

application:
    config:
        comment-service:
            url: http://comment-service:8081/comment-service/api/v1

minio:
    endpoint: http://minio:9000
    accessKey: ${MINIO_ROOT_USER}
    secretKey: ${MINIO_ROOT_PASSWORD}
    bucketName: blog-images
    createBucket: true
    external:
        public-url: http://minio:9000
        path: /minio-api
