eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 8080

spring:
    application:
        name: blog-service
    config:
        import: optional:configserver:http://localhost:8888
    datasource:
        url: jdbc:mysql://localhost:3306/whispers_of_zephyr_blogs
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:password}
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
            enabled: true

custom:
    image:
        path: "/utils/default blog image.jpeg"

application:
    config:
        comment-service:
            url: http://localhost:8081/api/v1
