# Use the appropriate JDK version
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /backend/user_service

# Copy the JAR file to the working directory
COPY target/user_service.jar .

# Expose the port the service listens on
EXPOSE 8083

# Set the entry point to run the service
ENTRYPOINT ["java", "-jar", "service1.jar"]
