# Use Maven image to build the application
FROM maven:3.9.5-eclipse-temurin-21-alpine AS build

# Set the working directory inside the container
WORKDIR /user_service

# Copy only the necessary files for dependency resolution
COPY pom.xml ./
COPY src ./src

# Run Maven to build the application and skip tests
RUN mvn clean package -DskipTests

# Use the appropriate JDK version
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /user_service

# Copy the JAR file to the working directory
COPY --from=build /user_service/target/user_service-0.0.1-SNAPSHOT.jar user_service.jar

# Expose the port the service listens on
EXPOSE 8083

# Set the entry point to run the service
ENTRYPOINT ["java", "-jar", "user_service.jar"]
