name: Blog Service CI

on:
    push:
        paths:
            - "blog_service/**"
        branches:
            - "**"

jobs:
    build-and-test:
        name: Build and Test Blog Service
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: blog_db
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

            rabbitmq:
                image: rabbitmq:3-management
                env:
                    RABBITMQ_DEFAULT_USER: guest
                    RABBITMQ_DEFAULT_PASS: guest
                ports:
                    - 5672:5672
                    - 15672:15672
                options: >-
                    --health-cmd="rabbitmq-diagnostics -q ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build Discovery Server Image
              run: docker build -t discovery_server:latest -f discovery_server/Dockerfile ./discovery_server

            - name: Run Discovery Server
              run: |
                  docker run -d --name discovery_server -p 8761:8761 discovery_server:latest
                  sleep 30  # Ensure Eureka Server is ready

            - name: Build Blog Service Image
              run: docker build -t blog_service:latest -f blog_service/Dockerfile ./blog_service

            - name: Run Blog Service
              run: |
                  docker run -d --name blog_service --network=host \
                  -e DB_USERNAME=root \
                  -e DB_PASSWORD=root \
                  -e RABBITMQ_USERNAME=guest \
                  -e RABBITMQ_PASSWORD=guest \
                  -e EUREKA_SERVER=http://localhost:8761/eureka \
                  blog_service:latest
                  sleep 20  # Allow service to start

            - name: Run Health Check
              run: |
                  curl --retry 5 --retry-delay 5 --fail http://localhost:8080/actuator/health

            - name: Stop and Remove Containers
              run: |
                  docker stop blog_service discovery_server
                  docker rm blog_service discovery_server
