name: Blog service CI

on:
    push:
        paths:
            - "blog_service/**"
        branches:
            - "**"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        env:
            working-directory: ./blog_service
        defaults:
            run:
                working-directory: ${{ env.working-directory }}

        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: 21
                  cache: "maven"

            # Start Eureka Server in the background
            - name: Start Eureka Server
              run: nohup mvn spring-boot:run > eureka.log 2>&1 &
              working-directory: ./discovery_server

            # Wait for Eureka to start
            - name: Wait for Eureka Server
              run: |
                  sleep 30  # Adjust time as needed to ensure Eureka is fully started

            - name: Build with Maven
              run: mvn clean package
              working-directory: ./blog_service

            - name: Verify blog service
              run: mvn verify
              working-directory: ./blog_service

            # Start Blog Service in the background
            - name: Run blog service
              run: nohup mvn spring-boot:run > blog_service.log 2>&1 &
              working-directory: ./blog_service
