# Use the appropriate JDK version
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory inside the container
WORKDIR /comment_service

# Copy the JAR file to the working directory
COPY target/comment_service-0.0.1-SNAPSHOT.jar comment_service.jar

# Expose the port the service listens on
EXPOSE 8081

# Set the entry point to run the service
ENTRYPOINT ["java", "-jar", "comment_service.jar"]
